/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-07 10:31:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>join</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/join.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Hi+Melody&family=Moirai+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"height:1000px !important;\">\r\n");
      out.write("\r\n");
      out.write("    <main style=\"height:100% !important;\">\r\n");
      out.write("\r\n");
      out.write("        <div id = \"logoDiv\">\r\n");
      out.write("\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/logo.png\" id=\"img0\"\r\n");
      out.write("                            style=\"width: 200px !important;\r\n");
      out.write("                                height: 100px !important;\">\r\n");
      out.write("            </a>                   \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <form action=\"join\" method=\"post\" onsubmit=\"return joinValidate()\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"height\"></div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"firstbox\">\r\n");
      out.write("                <article class = \"Articles\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/id.png\" id=\"img1\">\r\n");
      out.write("                    <input type=\"text\" class=\"inputs\" id=\"inputId\" name=\"inputId\" placeholder=\"아이디를 입력해주세요.\" autocomplete=\"off\">\r\n");
      out.write("                </article>\r\n");
      out.write("\r\n");
      out.write("                <article class = \"Articles\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/password.jpg\" id=\"img2\">\r\n");
      out.write("                    <input type=\"password\" class=\"inputs\" id=\"inputPw\" name=\"inputPw\" placeholder=\"비밀번호를 입력해주세요.\">\r\n");
      out.write("                </article>\r\n");
      out.write("\r\n");
      out.write("                <article class = \"Articles\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/password2.png\" id=\"img3\">\r\n");
      out.write("                    <input type=\"password\" class=\"inputs\" id=\"inputPwCheck\" name=\"inputPwCheck\" placeholder=\"비밀번호 확인을 입력해주세요.\">\r\n");
      out.write("                </article>\r\n");
      out.write("\r\n");
      out.write("                <div id=\"innerTextSpan1\"></div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"height\"></div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"secondBox\">\r\n");
      out.write("\r\n");
      out.write("                <article id=\"giveMargin\" class = \"Articles\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/id.png\" id=\"img5\">\r\n");
      out.write("                    <input type=\"text\" class=\"inputs\" id=\"memberNickname\" name=\"memberNickname\" placeholder=\"닉네임을 입력해주세요.\" autocomplete=\"off\">\r\n");
      out.write("                \r\n");
      out.write("                </article>\r\n");
      out.write("\r\n");
      out.write("                <article class = \"Articles\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/id.png\" id=\"img6\">\r\n");
      out.write("                    <input type=\"text\" class=\"inputs\" id=\"memberName\" name=\"memberName\" placeholder=\"이름을 입력해주세요.\" autocomplete=\"off\">\r\n");
      out.write("\r\n");
      out.write("                </article >\r\n");
      out.write("\r\n");
      out.write("                <article class = \"Articles\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/id.png\" id=\"img7\">\r\n");
      out.write("                    <input type=\"text\" class=\"inputs\" id=\"memberBirth\" name=\"memberBirth\" placeholder=\"생년월일을 8자리로 입력해주세요.(- 제외)\" autocomplete=\"off\">\r\n");
      out.write("                \r\n");
      out.write("                </article>\r\n");
      out.write("\r\n");
      out.write("                <article class = \"Articles\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/id.png\" id=\"img8\">\r\n");
      out.write("                 \r\n");
      out.write("                    <div id=\"selectDiv\">\r\n");
      out.write("                        <select id=\"regionSelect\" name=\"regionSelect\">\r\n");
      out.write("                            <option selected value=\"default\">주 활동지역을 선택해주세요.</option> <!-- 이거 선택안되게 하는법? -->\r\n");
      out.write("                            <option value=\"서울\">서울</option>\r\n");
      out.write("                            <option value=\"경기도\">경기도</option>\r\n");
      out.write("                            <option value=\"강원도\">강원도</option>\r\n");
      out.write("                            <option value=\"충청도\">충청도</option>\r\n");
      out.write("                            <option value=\"전라도\">전라도</option>\r\n");
      out.write("                            <option value=\"경상도\">경상도</option>\r\n");
      out.write("                            <option value=\"제주도\">제주도</option>\r\n");
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>    \r\n");
      out.write("\r\n");
      out.write("                </article>\r\n");
      out.write("\r\n");
      out.write("                <article class = \"Articles\"> \r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/id.png\" id=\"img10\">\r\n");
      out.write("                    <input type=\"text\" class=\"inputs\" id=\"memberPhone\" name=\"memberPhone\" placeholder=\"전화번호를 입력해주세요.(- 제외)\" autocomplete=\"off\">\r\n");
      out.write("\r\n");
      out.write("                </article>\r\n");
      out.write("\r\n");
      out.write("                <article class = \"Articles\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/id.png\" id=\"img11\"> \r\n");
      out.write("                    <div id=\"genderNationality\">\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"gender\">\r\n");
      out.write("                            <label for=\"man\" class=\"leftLabel\" id=\"manLabel\">\r\n");
      out.write("                                <div id = \"manDiv\">\r\n");
      out.write("                                    <input type=\"radio\" name=\"gender\" id=\"man\" class=\"radios\" value=\"남\">\r\n");
      out.write("                                    <span name=\"남\">남</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("\r\n");
      out.write("                            <label for=\"woman\" class=\"rightLabel\" id=\"womanLabel\">\r\n");
      out.write("                                <div id=\"womanDiv\">\r\n");
      out.write("                                    <input type=\"radio\" name=\"gender\" id=\"woman\" class=\"radios\" value=\"여\">\r\n");
      out.write("                                    <span name=\"여\">여</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"nationality\">\r\n");
      out.write("                            <label for=\"kor\" class=\"leftLabel\" id=\"korLabel\">\r\n");
      out.write("                                <div id=\"korDiv\">\r\n");
      out.write("                                    <input type=\"radio\" name=\"nation\" id=\"kor\" class=\"radios\" value=\"내국인\">\r\n");
      out.write("                                    <span>내국인</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("\r\n");
      out.write("                            <label for=\"foreign\" class=\"rightLabel\" id=\"forLabel\">\r\n");
      out.write("                                <div id=\"forDiv\"> \r\n");
      out.write("                                    <input type=\"radio\" name=\"nation\" id=\"foreign\" class=\"radios\" value=\"외국인\">\r\n");
      out.write("                                    <span>외국인</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article>\r\n");
      out.write("                \r\n");
      out.write("                <article class = \"Articles\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/id.png\" id=\"img4\">\r\n");
      out.write("                    <input type=\"email\" class=\"inputs\" id=\"inputEmail\" name=\"inputEmail\" placeholder=\"이메일을 입력해주세요.\" autocomplete=\"off\">\r\n");
      out.write("                    <button id=\"emailBtn\" type=\"button\">인증하기</button>\r\n");
      out.write("                </article>\r\n");
      out.write("\r\n");
      out.write("                <article class = \"Articles\" id=\"\">\r\n");
      out.write("                    <input type=\"hidden\" class=\"inputs\" id=\"authenticationInput\" placeholder=\"인증번호를 입력해주세요.\" class=\"inputs\">\r\n");
      out.write("                    <input type=\"hidden\" id=\"authenticationButton\">\r\n");
      out.write("                </article>\r\n");
      out.write("\r\n");
      out.write("                <div id=\"innerTextSpan2\" ></div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"height2\"></div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"thirdBox\">\r\n");
      out.write("                <button id=\"btn\">회원가입</button>\r\n");
      out.write("            </div>    \r\n");
      out.write("\r\n");
      out.write("            <div class=\"height2\"></div>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <footer>\r\n");
      out.write("\r\n");
      out.write("			<section class=\"find1\">\r\n");
      out.write("\r\n");
      out.write("				<a> 이용약관 | 개인정보 처리 방침 | 책임의 한계와 법적고지 | 회원정보 고객센터 </a>\r\n");
      out.write("\r\n");
      out.write("			</section>\r\n");
      out.write("\r\n");
      out.write("			<section class=\"find1\">\r\n");
      out.write("\r\n");
      out.write("				<section>\r\n");
      out.write("\r\n");
      out.write("					<a>Copyright &copy; 2023 OTSUMO CO., LTD. ALL rights reserved<span>|</span></a>\r\n");
      out.write("\r\n");
      out.write("				</section>\r\n");
      out.write("\r\n");
      out.write("			</section>\r\n");
      out.write("		</footer>\r\n");
      out.write("\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("<!--     <script>\r\n");
      out.write("        const contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("    </script>     -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/join.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
